config/routes.rb
Payment::Application.routes.draw do
  root :to => 'users#index'
  resources :users
  resources :payment_txns do
    post 'update_installment_record' 
  end

end

app/models/installment.rb
class Installment < ActiveRecord::Base
	belongs_to :payment_txn

	validates :scheduled_date, :presence => true

	INSTALLMENT_STATES = [
	  SCHEDULED = "Scheduled",
	  OVERDUE = "Overdue",
	  PAID = 'Paid'
	]

	after_create :update_payment_txn_record
	after_update :update_payment_txn_status

	def update_payment_txn_record
		payment_txn = self.payment_txn
		payment_txn.no_of_installments = payment_txn.installments.count
		payment_txn.save
	end

	def update_payment_txn_status
		payment_txn = self.payment_txn
		installment_states = payment_txn.installments.collect(&:status).uniq
		if installment_states.count == 1 && installment_states[0] == PAID
			payment_txn.status = PaymentTxn::PAID
		elsif installment_states.count > 1
			payment_txn.status = PaymentTxn::INPROGRESS
		end
		payment_txn.amount_paid = payment_txn.installments.where('status = ?', PAID).collect(&:installment_amount).sum
		payment_txn.remaining_amount = payment_txn.total_amount - payment_txn.discount - payment_txn.amount_paid
		payment_txn.save
	end

	def is_overdue?
		scheduled_date < Time.zone.today
	end

	def paid?
		status == Installment::PAID
	end
end

app/models/payment_txn.rb
class PaymentTxn < ActiveRecord::Base
	belongs_to :user
	has_many :installments, dependent: :destroy

	validates :total_amount, :presence => true, :numericality => true
	validates :discount, :presence => true, :numericality => true
	validate :discount_cant_be_more_than_total_amount
	validate :validate_total_amount_with_installment_amount

	accepts_nested_attributes_for :installments, :allow_destroy => true

	PAYMENTTXN_STATES = [
	  NEW = "New",
	  INPROGRESS = "Inprogress",
	  PAID = 'Paid'
	]

	before_create :set_defaults
	after_create :set_installments

	def validate_total_amount_with_installment_amount
		if self.installments.present?
			errors.add(:total_amount, "can't be more than total of installment amount.") if (self.total_amount - self.discount) != (self.installments.collect(&:installment_amount).sum)
		end
	end

	def discount_cant_be_more_than_total_amount
	  errors.add(:discount, "can't be more than total amount.") if discount > total_amount
	end

	def set_defaults
		self.status = NEW
		self.transaction_date = Time.zone.today
		self.remaining_amount = total_amount - discount
		self.amount_paid = 0
	end

	def set_installments
		unless self.installments.present?
			self.installments.create(:scheduled_date => Time.zone.today, :status => Installment::SCHEDULED, :content => 'One Installment', :installment_amount => total_amount - discount) 	
		end 
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :payment_txns, dependent: :destroy

	validates :name, :presence => true
	validates :email_id, :presence => true, :uniqueness => true
	validates_format_of :email_id, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

	accepts_nested_attributes_for :payment_txns, :allow_destroy => true

	def in_progress_payments
		payment_txns.where('status in (?)',[PaymentTxn::NEW,PaymentTxn::INPROGRESS])
	end

	def completed_payments		
		payment_txns.where('status = ?',PaymentTxn::PAID)		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payment_txns_controller.rb
class PaymentTxnsController < ApplicationController
  before_action :set_payment_txn, only: [:show, :edit, :update, :destroy]

  # GET /payment_txns
  # GET /payment_txns.json
  def index
    @user = User.find_by_id(params[:user_id])
    unless @user.present?
      flash[:danger] = "No User Found."
      redirect_to root_path
    else
      @payment_txns = @user.payment_txns.where('status in (?)', params[:status]).paginate(:page => params[:page], :per_page => 10)
      @status = params[:status]
    end
  end

  # GET /payment_txns/1
  # GET /payment_txns/1.json
  def show
  end

  # GET /payment_txns/new
  def new
    @user = User.find_by_id(params[:user_id])
    @payment_txn = PaymentTxn.new
    unless @user.present?
      flash[:danger] = "No User Found."
      redirect_to root_path
    end
  end

  # GET /payment_txns/1/edit
  def edit
  end

  # POST /payment_txns
  # POST /payment_txns.json
  def create
    @payment_txn = PaymentTxn.new(payment_txn_params)

    respond_to do |format|
      if @payment_txn.save
        format.html { redirect_to edit_payment_txn_path(@payment_txn), notice: 'Payment txn was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment_txn }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment_txn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_txns/1
  # PATCH/PUT /payment_txns/1.json
  def update
    respond_to do |format|
      if @payment_txn.update(payment_txn_params)
        format.html { redirect_to @payment_txn, notice: 'Payment txn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment_txn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_txns/1
  # DELETE /payment_txns/1.json
  def destroy
    @payment_txn.destroy
    respond_to do |format|
      format.html { redirect_to payment_txns_url }
      format.json { head :no_content }
    end
  end

  def update_installment_record
    @save_flag = false
    installment = Installment.find_by_id(params[:id])
    if installment.present? and params[:status].present?
      @payment_txn = installment.payment_txn
      installment.status = params[:status]
      installment.save
      @save_flag = true
    end
    respond_to do |format|
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_txn
      @payment_txn = PaymentTxn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_txn_params
      params.require(:payment_txn).permit(:total_amount, :discount, :user_id, installments_attributes: [:scheduled_date,:status, :content, :installment_amount, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
    params.require(:user).permit(:name, :email_id, payment_txns_attributes: [:total_amount, :discount, :_destroy, installments_attributes: [:scheduled_date, :status, :content, :installment_amount,:_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def installment_options
		options = {'Select' => ''}
		Installment::INSTALLMENT_STATES.each { |wait_list_state| options = options.merge({wait_list_state => wait_list_state}) }    
		options
	end
end

app/helpers/payment_txns_helper.rb
module PaymentTxnsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Payment
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css", :media => "all"
    = javascript_include_tag "https://code.jquery.com/jquery-1.12.4.js"
    = javascript_include_tag "https://code.jquery.com/ui/1.12.0/jquery-ui.js"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'shared/navbar'
    #page-wrapper{:style =>'padding: 15px 15px;min-height: 600px;background:#F3F3F3;'}
      %center
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
              = content_tag :div, msg, :id => "flash_#{name}"
      = yield
  :javascript
    $(".datepicker").datepicker({ dateFormat: "yy-mm-dd" });

app/views/payment_txns/_form.html.haml
= nested_form_for @payment_txn do |f|
  - if @payment_txn.errors.any?
    #error_explanation
      %h2
        = pluralize(@payment_txn.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @payment_txn.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      Name:
    .col-md-4
      = @user.name rescue @payment_txn.user.name
  %br
  .row
    .col-md-2
      Email Id
    .col-md-4
      = @user.email_id rescue @payment_txn.user.email_id
  %br
  .row
    .col-md-4
      %b Payment Entry
  %br
  .row
    .col-md-2
      Total Amount
    .col-md-4
      = f.text_field :total_amount, :class =>'form-control',:required => true
  %br
  .row
    .col-md-2
      Discount
    .col-md-4
      = f.text_field :discount, :class =>'form-control',:required => true
  = f.fields_for :installments do |i|
    %br
      .row
        .col-md-2
          %b Installment Entry
      %br
      .row
        .col-md-2
          Description
        .col-md-4
          = i.text_field :content, :class =>'form-control',:required => true
      %br
      .row
        .col-md-2
          Installment Amount
        .col-md-4
          = i.text_field :installment_amount, :class =>'form-control',:required => true
      %br
      .row
        .col-md-2
          Installment Date
        .col-md-4
          = i.text_field :scheduled_date, :class =>'form-control datepicker'
          = i.hidden_field :status, :value => Installment::SCHEDULED
        .col-md-2
          = i.link_to_remove "Remove Installment Entry"
    %br
  = f.link_to_add "Add Installment Entry",:installments, :class => 'btn btn-default'
  - user_id = @user.id rescue @payment_txn.user.id
  = f.hidden_field :user_id, :value => user_id
  %br
  %br
  .actions
    = f.submit 'Save', :class => 'btn btn-primary'
    = link_to 'Back', root_path, :class => 'btn btn-default'

app/views/payment_txns/_installment_details.html.haml
.row
  .col-md-6
    .well.well-lg
      %b User Details
      %br
      %br
      .row
        .col-md-2
          %b Name:
        .col-md-3
          = @payment_txn.user.name
      .row
        .col-md-2
          %b Email:
        .col-md-4
          = @payment_txn.user.email_id
      .row
        .col-md-2
          %b Status:
        .col-md-4
          = @payment_txn.status
  .col-md-6
    .well.well-lg
      %b Payment Details
      %br
      .row
        .col-md-4
          %b Total Amount:
        .col-md-8
          = @payment_txn.total_amount
      .row
        .col-md-4
          %b Discount:
        .col-md-8
          = @payment_txn.discount
      .row
        .col-md-4
          %b Paid Amount:
        .col-md-8
          = @payment_txn.amount_paid
      .row
        .col-md-4
          %b Remaining Amount:
        .col-md-8
          = @payment_txn.remaining_amount
- if @payment_txn.installments.present?
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th
          Content
        %th
          Amount
        %th
          Scheduled Date
        %th
          Status
        %th
          Update?
        %th
          Action
    %tbody
      - @payment_txn.installments.each_with_index do |installment, i|
        = form_tag "update_installment_record.js?id=#{installment.id}", :remote => true do
          %tr
            %td= installment.content 
            %td= installment.installment_amount
            %td= installment.scheduled_date.strftime('%d %b %Y')
            - if installment.is_overdue? && !installment.paid?
              %td Overdue
            - else
              %td= installment.status
            %td= select_tag :status, options_for_select(installment_options)
            %td= submit_tag :Save,:class => 'btn btn-primary'
- else
  = link_to 'Create Installment', root_path, :class => 'btn btn-default'

app/views/payment_txns/edit.html.haml
%h1 Payment Details
%br
.installment_details
  = render 'installment_details'
%br/
= link_to 'Back', root_path, :class => 'btn btn-default'

app/views/payment_txns/index.html.haml
%h1 Payment Transactions
%br
%center
  = will_paginate @payment_txns
.row
  .col-md-2
    Name:
  .col-md-4
    = @user.name
.row
  .col-md-2
    Email Id:
  .col-md-4
    = @user.email_id
.row
  .col-md-2
    Status:
  .col-md-4
    = @status.join(', ').html_safe
%br
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th
        ID
      %th
        Total Amount
      %th
        Discount
      %th
        Amount Paid
      %th
        Remaining Amount
      %th 
        Installments
      %th
        Status
      %th
        Transaction Date
      / %th
      /   Actions 
  %tbody
    - @payment_txns.each do |payment_txn|
      %tr
        %td= payment_txn.id
        %td= payment_txn.total_amount
        %td= payment_txn.discount
        %td= payment_txn.amount_paid
        %td= payment_txn.remaining_amount
        %td= link_to payment_txn.no_of_installments.to_i, edit_payment_txn_path(payment_txn)
        %td= payment_txn.status
        %td= payment_txn.transaction_date.strftime('%d %b %Y')
        / %td= link_to 'Edit', edit_payment_txn_path(payment_txn), :class => 'btn btn-default'
%br/
= link_to 'Back', root_path, :class => 'btn btn-default'

app/views/payment_txns/new.html.erb
<h1>New payment_txn</h1>

<%= render 'form' %>

app/views/payment_txns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_txn_path(@payment_txn) %> |
<%= link_to 'Back', payment_txns_path %>

app/views/payment_txns/update_installment_record.js.erb
<% if @save_flag  %>
  $('.installment_details').html('<%= escape_javascript(render(:partial => 'installment_details', :locals => {:@payment_txn => @payment_txn})) %>');
<% else %>
  alert("Something went wrong.")
<% end %>

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Payment Tracker
    

app/views/users/_add_payment.html.haml
= nested_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      Name:
    .col-md-4
      = user.name
  %br
  .row
    .col-md-2
      Email Id
    .col-md-4
      = user.email_id
  %br
  .div
    = f.fields_for :payment_txns do |pt|
      .row
        .col-md-2
          Total Amount
        .col-md-4
          = pt.text_field :total_amount, :class =>'form-control',:required => true
      %br
      .row
        .col-md-2
          Discount
        .col-md-4
          = pt.text_field :discount, :class =>'form-control',:required => true
        .col-md-2
          = pt.link_to_remove "Remove Payment Entry"
      = pt.fields_for :installments do |i|
        %br
        .row
          .col-md-2
            Scheduled Date
          .col-md-4
            = i.text_field :scheduled_date, :class =>'form-control datepicker'
          .col-md-2
            = i.link_to_remove "Remove Installment Entry"
      %br
      = pt.link_to_add "Add Installment Entry",:installments, :class => 'btn btn-default'
      %br
    = f.link_to_add "Add Payment Entry", :payment_txns, :class => 'btn btn-default'
  %br
  .actions
    = f.submit 'Save', :class => 'btn btn-primary'
    = link_to 'Back', payment_txns_path, :class => 'btn btn-default'

app/views/users/_form.html.haml
= nested_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-2
      Name
    .col-md-4
      = f.text_field :name,:class =>'form-control', :required => true
  %br
  .row
    .col-md-2
      Email Id
    .col-md-4
      = f.text_field :email_id,:class =>'form-control', :required => true
  %br
  = f.fields_for :payment_txns do |pt|
    .row
      .col-md-4
        %b Payment Entry
    %br
    .row
      .col-md-2
        Total Amount
      .col-md-4
        = pt.text_field :total_amount, :class =>'form-control',:required => true
    %br
    .row
      .col-md-2
        Discount
      .col-md-4
        = pt.text_field :discount, :class =>'form-control',:required => true
      .col-md-2
        / = pt.link_to_remove "Remove Payment Entry"
    = pt.fields_for :installments do |i|
      %br
      .row
        .col-md-2
          %b Installment Entry
      %br
      .row
        .col-md-2
          Description
        .col-md-4
          = i.text_field :content, :class =>'form-control',:required => true
      %br
      .row
        .col-md-2
          Installment Amount
        .col-md-4
          = i.text_field :installment_amount, :class =>'form-control',:required => true
      %br
      .row
        .col-md-2
          Installment Date
        .col-md-4
          = i.text_field :scheduled_date, :class =>'form-control datepicker'
          = i.hidden_field :status, :value => Installment::SCHEDULED
        .col-md-2
          = i.link_to_remove "Remove Installment Entry"
    %br
    = pt.link_to_add "Add Installment Entry",:installments, :class => 'btn btn-default'
    %br
  = f.link_to_add "Add Payment Entry", :payment_txns, :class => 'btn btn-default hideAfterClick'
  %br
  %br
  .actions
    = f.submit 'Create User', :class => 'btn btn-primary'
    = link_to 'Back', root_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Users
%center
  = will_paginate @users
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th 
        User
      %th
        Email ID
      %th
        No. Of Txns
      %th
        Completed
      %th
        Pending
      %th
        Actions 
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email_id
        %td= link_to user.payment_txns.count, payment_txns_path(:user_id => user.id ,:status => [PaymentTxn::NEW,PaymentTxn::INPROGRESS,PaymentTxn::PAID])
        %td= link_to user.completed_payments.count, payment_txns_path(:user_id => user.id ,:status => [PaymentTxn::PAID])
        %td= link_to user.in_progress_payments.count, payment_txns_path(:user_id => user.id ,:status => [PaymentTxn::NEW,PaymentTxn::INPROGRESS])
        %td= link_to 'Add New Txn', new_payment_txn_path(:user_id => user.id), :class => 'btn btn-default'
%br/
= link_to 'Create User', new_user_path, :class => 'btn btn-default'

app/views/users/new.html.haml
%h1 New user
= render 'form'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email_id



= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path